# Generated by Django 4.1.7 on 2023-03-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nike',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
